# Multi-Atom RNA Structure Prediction Model Configuration
# Optimized for predicting multiple atoms per nucleotide

data:
  train_sequence_file: 'datasets/stanford-rna-3d-folding/train_sequences.csv'
  train_labels_file: 'datasets/stanford-rna-3d-folding/train_labels.csv'
  val_sequence_file: 'datasets/stanford-rna-3d-folding/validation_sequences.csv'
  val_labels_file: 'datasets/stanford-rna-3d-folding/validation_labels.csv'
  test_sequence_file: 'datasets/stanford-rna-3d-folding/test_sequences.csv'
  batch_size: 32
  num_workers: 0  # No multiprocessing for Kaggle
  sequence_bucketing: true

model:
  name: 'RNAFoldingModel'
  params:
    vocab_size: 5  # A, U, G, C, N (padding)
    embedding_dim: 256  # Larger embedding for multi-atom representation
    hidden_dim: 512  # Larger hidden dimensions for predicting complex structures
    num_layers: 6  # More transformer layers for deeper representation
    num_heads: 8  # Multi-head attention
    dropout: 0.1  # Regularization
    num_atoms: 5  # Default number of atoms per nucleotide
    multi_atom_mode: true  # Enable multi-atom mode
    coord_dims: 3  # 3D coordinates (x, y, z)
    max_seq_len: 500  # Maximum sequence length
    use_rna_constraints: true  # Enable RNA-specific constraints
    bond_length_weight: 1.5  # Stronger weight for bond length in multi-atom mode
    bond_angle_weight: 1.5  # Stronger weight for bond angles in multi-atom mode
    steric_clash_weight: 2.0  # Stronger steric clash penalty in multi-atom mode
    watson_crick_weight: 2.0  # Weight for Watson-Crick base pairing
    normalize_coords: true  # Normalize coordinates in the model
    use_relative_attention: true  # Use RNA-specific relative attention

training:
  num_epochs: 40  # More epochs for more complex task
  learning_rate: 3.0e-5  # Lower learning rate for more stable training
  weight_decay: 2.0e-5  # Stronger regularization
  lr_scheduler: 'plateau'
  lr_scheduler_params:
    factor: 0.5  # Reduce LR by half when plateau
    patience: 3  # Wait 3 epochs before reducing LR
    verbose: true
  gradient_clip_val: 1.0  # Prevent exploding gradients
  early_stopping: true
  patience: 7  # Longer patience for more complex multi-atom model
  checkpoint_dir: 'models/stanford-rna-3d-folding/multi_atom'

transforms:
  train:
    normalize_coords: true  # Normalize coordinates to be scale-invariant
    random_rotation: true  # Apply random rotations for data augmentation
    position_noise: 0.03  # Slightly less noise for multi-atom precision
    atom_mask_prob: 0.05  # Lower masking probability for multi-atom
  val:
    normalize_coords: true
    random_rotation: false  # No rotation for validation
    position_noise: 0.0  # No noise for validation
    atom_mask_prob: 0.0  # No masking for validation

misc:
  seed: 42  # Random seed for reproducibility 