# Configuration for quick testing of RNA 3D Structure Prediction

# General settings
experiment_name: "rna_folding_quick_test"
seed: 42
device: "cpu"  # Force CPU usage

# Data settings
data_dir: "datasets/stanford-rna-3d-folding"
save_dir: "models/stanford-rna-3d-folding/quick_test"
num_workers: 2  # Reduced worker count

# Model architecture - smaller model
vocab_size: 5  # A, U, G, C, N (padding)
embedding_dim: 64  # Reduced from 128
hidden_dim: 128  # Reduced from 256
num_layers: 2  # Reduced from 4
num_heads: 4  # Reduced from 8
dropout: 0.1
num_atoms: 5  # 5 atoms per nucleotide
coord_dims: 3  # 3D coordinates (x, y, z)
max_seq_len: 500

# Training settings - faster training
batch_size: 8  # Reduced from 16
num_epochs: 5  # Reduced from 100
learning_rate: 5.0e-4
weight_decay: 1.0e-5
patience: 3  # Reduced from 15

# Moderate physics-based constraint weights
bond_length_weight: 0.3
bond_angle_weight: 0.3
steric_clash_weight: 0.5

# Data transforms and augmentation
normalize_coords: true
random_rotation: true
random_noise: 0.05
jitter_strength: 0.02
atom_mask_prob: 0.1 